apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepageserver-primary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sawantalwar85/argo1.git'
    path: manifests
    targetRevision: master
  destination:
    server: 'https://172.25.232.191:6443'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
