apiVersion: apps/v1
kind: Deployment
metadata:
 name: stable
spec:
 replicas: 9
 selector:
  matchLabels:
    app: stable  ##it can be anything                                
 template:
  metadata:
   labels:
     app: stable
  spec:
    containers:
        - name: abc
          image: quay.io/gauravkumar9130/production:v1

